"""Consolidate User model and add authentication tables

Revision ID: e7aa0867203d
Revises: b68429ce9c72
Create Date: 2025-11-30 05:19:42.981318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7aa0867203d'
down_revision: Union[str, None] = 'b68429ce9c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Check database type
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == 'postgresql'

    # PostgreSQL requires renaming column BEFORE creating FK references
    # SQLite can handle it in any order with batch mode
    if is_postgresql:
        # STEP 1 (PostgreSQL): Modify users table first
        _upgrade_users_table()
        _upgrade_related_tables()
        # STEP 2 (PostgreSQL): Create auth tables
        _create_auth_tables()
    else:
        # SQLite order (original)
        _create_auth_tables()
        _upgrade_related_tables()
        _upgrade_users_table()


def _create_auth_tables():
    """Create authentication tables"""
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Verification token'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Token expiration'),
    sa.Column('verified', sa.Boolean(), nullable=True, comment='Verification status'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='Verification timestamp'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Token creation time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Reset token'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Token expiration'),
    sa.Column('used', sa.Boolean(), nullable=True, comment='Token usage status'),
    sa.Column('used_at', sa.DateTime(), nullable=True, comment='Token usage timestamp'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Token creation time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_jti', sa.String(length=255), nullable=False, comment='JWT Token ID'),
    sa.Column('token_type', sa.String(length=20), nullable=True, comment='access or refresh'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Token expiration time'),
    sa.Column('revoked', sa.Boolean(), nullable=True, comment='Token revocation status'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='Revocation timestamp'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Client user agent'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Session creation time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_token_jti'), ['token_jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False, comment='API key name/description'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='API key value'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Key active status'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Last usage timestamp'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Optional expiration'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Key creation time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_keys_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_api_keys_user_id'), ['user_id'], unique=False)


def _upgrade_related_tables():
    """Upgrade swing trading tables with new FK constraints"""
    # NOTE: Keeping subscriptions and transactions tables (managed separately)
    # These tables exist but are not being modified in this migration

    bind = op.get_bind()
    is_postgresql = bind.dialect.name == 'postgresql'

    if is_postgresql:
        # PostgreSQL: Use direct ALTER TABLE commands
        # Drop old FK constraints (referencing user_id), create new ones (referencing id)
        # Note: PostgreSQL FK names may be auto-generated, so we drop by finding them first

        # user_configs: add columns first, then update FK
        op.add_column('user_configs', sa.Column('budget_per_position_krw', sa.Integer(), nullable=True))
        op.add_column('user_configs', sa.Column('monitored_coins', sa.JSON(), nullable=True))
        op.add_column('user_configs', sa.Column('auto_trading_enabled', sa.Boolean(), nullable=True))

        # For FK updates, PostgreSQL will handle them automatically since we renamed user_id to id
        # The FK constraints will continue to work because the column data didn't change

    else:
        # SQLite: Use batch mode with table recreation
        # Use recreate='always' for SQLite - it automatically handles foreign key changes
        # No need to explicitly drop constraints when recreating the table
        with op.batch_alter_table('swing_position_history', schema=None, recreate='always') as batch_op:
            batch_op.create_foreign_key('fk_swing_position_history_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')

        with op.batch_alter_table('swing_positions', schema=None, recreate='always') as batch_op:
            batch_op.create_foreign_key('fk_swing_positions_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')

        with op.batch_alter_table('swing_trading_logs', schema=None, recreate='always') as batch_op:
            batch_op.create_foreign_key('fk_swing_trading_logs_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')

        with op.batch_alter_table('user_configs', schema=None, recreate='always') as batch_op:
            batch_op.add_column(sa.Column('budget_per_position_krw', sa.Integer(), nullable=True, comment='Budget per position in KRW'))
            batch_op.add_column(sa.Column('monitored_coins', sa.JSON(), nullable=True, comment='List of monitored coin symbols'))
            batch_op.add_column(sa.Column('auto_trading_enabled', sa.Boolean(), nullable=True, comment='Auto trading enabled'))
            batch_op.create_foreign_key('fk_user_configs_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')


def _upgrade_users_table():
    """Upgrade users table with new columns and rename PK"""
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == 'postgresql'

    if is_postgresql:
        # PostgreSQL: Use direct ALTER TABLE commands
        # Step 1: Rename column
        op.alter_column('users', 'user_id', new_column_name='id')

        # Step 2: Add new columns
        op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
        op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
        op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
        op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
        op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))

        # Step 3: Modify existing columns
        op.alter_column('users', 'email', nullable=False)
        op.alter_column('users', 'api_key', nullable=True)

        # Step 4: Add indexes
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)

    else:
        # SQLite: Use batch mode with table recreation
        with op.batch_alter_table('users', schema=None, recreate='always') as batch_op:
            # Rename user_id to id (SQLite will preserve values during table recreation)
            batch_op.alter_column('user_id',
                   new_column_name='id',
                   existing_type=sa.Integer(),
                   nullable=False,
                   comment='User ID')

            # Add new authentication columns
            batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Bcrypt hashed password'))
            batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True, comment='Email verification status (new name)'))
            batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True, comment='Email verification timestamp'))
            batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='Last successful login'))
            batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True, comment='Full name'))
            batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True, comment='Phone number'))

            # Modify existing columns
            batch_op.alter_column('email',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
            batch_op.alter_column('api_key',
                   existing_type=sa.VARCHAR(length=64),
                   nullable=True)

            # Add indexes
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
            batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None, recreate='always') as batch_op:
        # Rename id back to user_id
        batch_op.alter_column('id',
               new_column_name='user_id',
               existing_type=sa.Integer(),
               nullable=False)

        # Drop indexes
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

        # Revert column changes
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

        # Drop added columns
        batch_op.drop_column('phone')
        batch_op.drop_column('full_name')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('user_configs', schema=None, recreate='always') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('auto_trading_enabled')
        batch_op.drop_column('monitored_coins')
        batch_op.drop_column('budget_per_position_krw')

    with op.batch_alter_table('swing_trading_logs', schema=None, recreate='always') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('swing_positions', schema=None, recreate='always') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('swing_position_history', schema=None, recreate='always') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # NOTE: Not recreating subscriptions/transactions tables - they were not dropped

    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_api_keys_api_key'))

    op.drop_table('user_api_keys')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_jti'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_token'))

    op.drop_table('password_resets')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_token'))

    op.drop_table('email_verifications')
    # ### end Alembic commands ###
