/**
 * Coin Information Module
 * Upbit KRW 마켓 코인 정보 (230+ coins)
 * Logo source: cryptoicon-api.pages.dev
 */

// Coin information mapping (All 230 Upbit KRW markets)
const COIN_INFO = {
    'WAXP': { name: '왁스', logo: 'https://cryptoicon-api.pages.dev/api/icon/waxp' },
    'CARV': { name: '카브', logo: 'https://cryptoicon-api.pages.dev/api/icon/carv' },
    'LSK': { name: '리스크', logo: 'https://cryptoicon-api.pages.dev/api/icon/lsk' },
    '0G': { name: '제로지', logo: 'https://cryptoicon-api.pages.dev/api/icon/0g' },
    'BORA': { name: '보라', logo: 'https://cryptoicon-api.pages.dev/api/icon/bora' },
    'PUNDIX': { name: '펀디엑스', logo: 'https://cryptoicon-api.pages.dev/api/icon/pundix' },
    'USD1': { name: '월드리버티파이낸셜유에스디', logo: 'https://cryptoicon-api.pages.dev/api/icon/usd1' },
    'BAT': { name: '베이직어텐션토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/bat' },
    'HUNT': { name: '헌트', logo: 'https://cryptoicon-api.pages.dev/api/icon/hunt' },
    'PENGU': { name: '펏지펭귄', logo: 'https://cryptoicon-api.pages.dev/api/icon/pengu' },
    'FIL': { name: '파일코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/fil' },
    'BEAM': { name: '빔', logo: 'https://cryptoicon-api.pages.dev/api/icon/beam' },
    'DOOD': { name: '두들즈', logo: 'https://cryptoicon-api.pages.dev/api/icon/dood' },
    'WAVES': { name: '웨이브', logo: 'https://cryptoicon-api.pages.dev/api/icon/waves' },
    'USDC': { name: '유에스디코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/usdc' },
    'MOVE': { name: '무브먼트', logo: 'https://cryptoicon-api.pages.dev/api/icon/move' },
    'TREE': { name: '트리하우스', logo: 'https://cryptoicon-api.pages.dev/api/icon/tree' },
    'AERGO': { name: '아르고', logo: 'https://cryptoicon-api.pages.dev/api/icon/aergo' },
    'WET': { name: '휴미디파이', logo: 'https://cryptoicon-api.pages.dev/api/icon/wet' },
    'USDT': { name: '테더', logo: 'https://cryptoicon-api.pages.dev/api/icon/usdt' },
    '2Z': { name: '더블제로', logo: 'https://cryptoicon-api.pages.dev/api/icon/2z' },
    'BOUNTY': { name: '체인바운티', logo: 'https://cryptoicon-api.pages.dev/api/icon/bounty' },
    'KAITO': { name: '카이토', logo: 'https://cryptoicon-api.pages.dev/api/icon/kaito' },
    'LPT': { name: '라이브피어', logo: 'https://cryptoicon-api.pages.dev/api/icon/lpt' },
    'BLAST': { name: '블라스트', logo: 'https://cryptoicon-api.pages.dev/api/icon/blast' },
    'DKA': { name: '디카르고', logo: 'https://cryptoicon-api.pages.dev/api/icon/dka' },
    'ANKR': { name: '앵커', logo: 'https://cryptoicon-api.pages.dev/api/icon/ankr' },
    'ALGO': { name: '알고랜드', logo: 'https://cryptoicon-api.pages.dev/api/icon/algo' },
    'SHIB': { name: '시바이누', logo: 'https://cryptoicon-api.pages.dev/api/icon/shib' },
    'UNI': { name: '유니스왑', logo: 'https://cryptoicon-api.pages.dev/api/icon/uni' },
    'BIO': { name: '바이오프로토콜', logo: 'https://cryptoicon-api.pages.dev/api/icon/bio' },
    'WLFI': { name: '월드리버티파이낸셜', logo: 'https://cryptoicon-api.pages.dev/api/icon/wlfi' },
    'TOKAMAK': { name: '토카막네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/tokamak' },
    'CYBER': { name: '사이버', logo: 'https://cryptoicon-api.pages.dev/api/icon/cyber' },
    'DOGE': { name: '도지코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/doge' },
    'WLD': { name: '월드코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/wld' },
    'PEPE': { name: '페페', logo: 'https://cryptoicon-api.pages.dev/api/icon/pepe' },
    'HBAR': { name: '헤데라', logo: 'https://cryptoicon-api.pages.dev/api/icon/hbar' },
    'BCH': { name: '비트코인캐시', logo: 'https://cryptoicon-api.pages.dev/api/icon/bch' },
    'NEWT': { name: '뉴턴프로토콜', logo: 'https://cryptoicon-api.pages.dev/api/icon/newt' },
    'SEI': { name: '세이', logo: 'https://cryptoicon-api.pages.dev/api/icon/sei' },
    'BONK': { name: '봉크', logo: 'https://cryptoicon-api.pages.dev/api/icon/bonk' },
    'JST': { name: '저스트', logo: 'https://cryptoicon-api.pages.dev/api/icon/jst' },
    'AAVE': { name: '에이브', logo: 'https://cryptoicon-api.pages.dev/api/icon/aave' },
    'JTO': { name: '지토', logo: 'https://cryptoicon-api.pages.dev/api/icon/jto' },
    'JUP': { name: '주피터', logo: 'https://cryptoicon-api.pages.dev/api/icon/jup' },
    'FLOW': { name: '플로우', logo: 'https://cryptoicon-api.pages.dev/api/icon/flow' },
    'ALT': { name: '알트레이어', logo: 'https://cryptoicon-api.pages.dev/api/icon/alt' },
    'LAYER': { name: '솔레이어', logo: 'https://cryptoicon-api.pages.dev/api/icon/layer' },
    'TRX': { name: '트론', logo: 'https://cryptoicon-api.pages.dev/api/icon/trx' },
    'POWR': { name: '파워렛저', logo: 'https://cryptoicon-api.pages.dev/api/icon/powr' },
    'ATOM': { name: '코스모스', logo: 'https://cryptoicon-api.pages.dev/api/icon/atom' },
    'ARKM': { name: '아캄', logo: 'https://cryptoicon-api.pages.dev/api/icon/arkm' },
    'CRO': { name: '크로노스', logo: 'https://cryptoicon-api.pages.dev/api/icon/cro' },
    'NXPC': { name: '넥스페이스', logo: 'https://cryptoicon-api.pages.dev/api/icon/nxpc' },
    'A': { name: '볼타', logo: 'https://cryptoicon-api.pages.dev/api/icon/a' },
    'TRUMP': { name: '오피셜트럼프', logo: 'https://cryptoicon-api.pages.dev/api/icon/trump' },
    'F': { name: '신퓨처스', logo: 'https://cryptoicon-api.pages.dev/api/icon/f' },
    'G': { name: '그래비티', logo: 'https://cryptoicon-api.pages.dev/api/icon/g' },
    'CELO': { name: '셀로', logo: 'https://cryptoicon-api.pages.dev/api/icon/celo' },
    'AERO': { name: '에어로드롬파이낸스', logo: 'https://cryptoicon-api.pages.dev/api/icon/aero' },
    'CTC': { name: '크레딧코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/ctc' },
    'ANIME': { name: '애니메코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/anime' },
    'APT': { name: '앱토스', logo: 'https://cryptoicon-api.pages.dev/api/icon/apt' },
    'MOCA': { name: '모카네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/moca' },
    'API3': { name: '에이피아이쓰리', logo: 'https://cryptoicon-api.pages.dev/api/icon/api3' },
    'AHT': { name: '아하토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/aht' },
    'EGLD': { name: '멀티버스엑스', logo: 'https://cryptoicon-api.pages.dev/api/icon/egld' },
    'ERA': { name: '칼데라', logo: 'https://cryptoicon-api.pages.dev/api/icon/era' },
    'FF': { name: '팔콘파이낸스', logo: 'https://cryptoicon-api.pages.dev/api/icon/ff' },
    'PLUME': { name: '플룸', logo: 'https://cryptoicon-api.pages.dev/api/icon/plume' },
    'NEO': { name: '네오', logo: 'https://cryptoicon-api.pages.dev/api/icon/neo' },
    'ETC': { name: '이더리움클래식', logo: 'https://cryptoicon-api.pages.dev/api/icon/etc' },
    'IOTA': { name: '아이오타', logo: 'https://cryptoicon-api.pages.dev/api/icon/iota' },
    'IOST': { name: '아이오에스티', logo: 'https://cryptoicon-api.pages.dev/api/icon/iost' },
    'AKT': { name: '아카시네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/akt' },
    'COW': { name: '카우프로토콜', logo: 'https://cryptoicon-api.pages.dev/api/icon/cow' },
    'VIRTUAL': { name: '버추얼프로토콜', logo: 'https://cryptoicon-api.pages.dev/api/icon/virtual' },
    'ETH': { name: '이더리움', logo: 'https://cryptoicon-api.pages.dev/api/icon/eth' },
    'IQ': { name: '아이큐', logo: 'https://cryptoicon-api.pages.dev/api/icon/iq' },
    'IP': { name: '스토리', logo: 'https://cryptoicon-api.pages.dev/api/icon/ip' },
    'NEAR': { name: '니어프로토콜', logo: 'https://cryptoicon-api.pages.dev/api/icon/near' },
    'RVN': { name: '레이븐코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/rvn' },
    'AGLD': { name: '어드벤처골드', logo: 'https://cryptoicon-api.pages.dev/api/icon/agld' },
    'ID': { name: '스페이스아이디', logo: 'https://cryptoicon-api.pages.dev/api/icon/id' },
    'IN': { name: '인피닛', logo: 'https://cryptoicon-api.pages.dev/api/icon/in' },
    'NOM': { name: '노미나', logo: 'https://cryptoicon-api.pages.dev/api/icon/nom' },
    'WAL': { name: '월러스', logo: 'https://cryptoicon-api.pages.dev/api/icon/wal' },
    'PENDLE': { name: '펜들', logo: 'https://cryptoicon-api.pages.dev/api/icon/pendle' },
    'BLUR': { name: '블러', logo: 'https://cryptoicon-api.pages.dev/api/icon/blur' },
    'AWE': { name: '에이더블유이', logo: 'https://cryptoicon-api.pages.dev/api/icon/awe' },
    'THETA': { name: '쎄타토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/theta' },
    'AXL': { name: '엑셀라', logo: 'https://cryptoicon-api.pages.dev/api/icon/axl' },
    'HP': { name: '히포프로토콜', logo: 'https://cryptoicon-api.pages.dev/api/icon/hp' },
    'SAND': { name: '샌드박스', logo: 'https://cryptoicon-api.pages.dev/api/icon/sand' },
    'WCT': { name: '월렛커넥트', logo: 'https://cryptoicon-api.pages.dev/api/icon/wct' },
    'YGG': { name: '일드길드게임즈', logo: 'https://cryptoicon-api.pages.dev/api/icon/ygg' },
    'AXS': { name: '엑시인피니티', logo: 'https://cryptoicon-api.pages.dev/api/icon/axs' },
    'ARDR': { name: '아더', logo: 'https://cryptoicon-api.pages.dev/api/icon/ardr' },
    'AQT': { name: '알파쿼크', logo: 'https://cryptoicon-api.pages.dev/api/icon/aqt' },
    'ME': { name: '매직에덴', logo: 'https://cryptoicon-api.pages.dev/api/icon/me' },
    'TRUST': { name: '인튜이션', logo: 'https://cryptoicon-api.pages.dev/api/icon/trust' },
    'SONIC': { name: '소닉SVM', logo: 'https://cryptoicon-api.pages.dev/api/icon/sonic' },
    'ARB': { name: '아비트럼', logo: 'https://cryptoicon-api.pages.dev/api/icon/arb' },
    'POL': { name: '폴리곤에코시스템토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/pol' },
    'CVC': { name: '시빅', logo: 'https://cryptoicon-api.pages.dev/api/icon/cvc' },
    'T': { name: '쓰레스홀드', logo: 'https://cryptoicon-api.pages.dev/api/icon/t' },
    'W': { name: '웜홀', logo: 'https://cryptoicon-api.pages.dev/api/icon/w' },
    'ARK': { name: '아크', logo: 'https://cryptoicon-api.pages.dev/api/icon/ark' },
    'AVNT': { name: '아반티스', logo: 'https://cryptoicon-api.pages.dev/api/icon/avnt' },
    'LA': { name: '라그랑주', logo: 'https://cryptoicon-api.pages.dev/api/icon/la' },
    'HYPER': { name: '하이퍼레인', logo: 'https://cryptoicon-api.pages.dev/api/icon/hyper' },
    'ATH': { name: '에이셔', logo: 'https://cryptoicon-api.pages.dev/api/icon/ath' },
    'TAIKO': { name: '타이코', logo: 'https://cryptoicon-api.pages.dev/api/icon/taiko' },
    'AVAX': { name: '아발란체', logo: 'https://cryptoicon-api.pages.dev/api/icon/avax' },
    'CPOOL': { name: '클리어풀', logo: 'https://cryptoicon-api.pages.dev/api/icon/cpool' },
    'IMX': { name: '이뮤터블엑스', logo: 'https://cryptoicon-api.pages.dev/api/icon/imx' },
    'SC': { name: '시아코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/sc' },
    'INJ': { name: '인젝티브', logo: 'https://cryptoicon-api.pages.dev/api/icon/inj' },
    'MVL': { name: '엠블', logo: 'https://cryptoicon-api.pages.dev/api/icon/mvl' },
    'HIVE': { name: '하이브', logo: 'https://cryptoicon-api.pages.dev/api/icon/hive' },
    'CBK': { name: '코박토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/cbk' },
    'OM': { name: '만트라', logo: 'https://cryptoicon-api.pages.dev/api/icon/om' },
    'XLM': { name: '스텔라루멘', logo: 'https://cryptoicon-api.pages.dev/api/icon/xlm' },
    'OP': { name: '옵티미즘', logo: 'https://cryptoicon-api.pages.dev/api/icon/op' },
    'SAFE': { name: '세이프', logo: 'https://cryptoicon-api.pages.dev/api/icon/safe' },
    'GLM': { name: '골렘', logo: 'https://cryptoicon-api.pages.dev/api/icon/glm' },
    'SUPER': { name: '슈퍼버스', logo: 'https://cryptoicon-api.pages.dev/api/icon/super' },
    'LINEA': { name: '리네아', logo: 'https://cryptoicon-api.pages.dev/api/icon/linea' },
    'KERNEL': { name: '커널다오', logo: 'https://cryptoicon-api.pages.dev/api/icon/kernel' },
    'POKT': { name: '포켓네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/pokt' },
    'ZKC': { name: '바운드리스', logo: 'https://cryptoicon-api.pages.dev/api/icon/zkc' },
    'KNC': { name: '카이버네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/knc' },
    'AUCTION': { name: '바운스토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/auction' },
    'ORDER': { name: '오덜리', logo: 'https://cryptoicon-api.pages.dev/api/icon/order' },
    'DRIFT': { name: '드리프트', logo: 'https://cryptoicon-api.pages.dev/api/icon/drift' },
    'FCT2': { name: '피르마체인', logo: 'https://cryptoicon-api.pages.dev/api/icon/fct2' },
    'MTL': { name: '메탈', logo: 'https://cryptoicon-api.pages.dev/api/icon/mtl' },
    'VET': { name: '비체인', logo: 'https://cryptoicon-api.pages.dev/api/icon/vet' },
    'QTUM': { name: '퀀텀', logo: 'https://cryptoicon-api.pages.dev/api/icon/qtum' },
    'TT': { name: '썬더코어', logo: 'https://cryptoicon-api.pages.dev/api/icon/tt' },
    'LINK': { name: '체인링크', logo: 'https://cryptoicon-api.pages.dev/api/icon/link' },
    'XRP': { name: '엑스알피(리플)', logo: 'https://cryptoicon-api.pages.dev/api/icon/xrp' },
    'CHZ': { name: '칠리즈', logo: 'https://cryptoicon-api.pages.dev/api/icon/chz' },
    'ASTR': { name: '아스타', logo: 'https://cryptoicon-api.pages.dev/api/icon/astr' },
    'STORJ': { name: '스토리지', logo: 'https://cryptoicon-api.pages.dev/api/icon/storj' },
    'ENA': { name: '에테나', logo: 'https://cryptoicon-api.pages.dev/api/icon/ena' },
    'MANA': { name: '디센트럴랜드', logo: 'https://cryptoicon-api.pages.dev/api/icon/mana' },
    'OPEN': { name: '오픈렛저', logo: 'https://cryptoicon-api.pages.dev/api/icon/open' },
    'GRS': { name: '그로스톨코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/grs' },
    'PYTH': { name: '피스네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/pyth' },
    'ENS': { name: '이더리움네임서비스', logo: 'https://cryptoicon-api.pages.dev/api/icon/ens' },
    'GRT': { name: '더그래프', logo: 'https://cryptoicon-api.pages.dev/api/icon/grt' },
    'PUMP': { name: '펌프펀', logo: 'https://cryptoicon-api.pages.dev/api/icon/pump' },
    'XTZ': { name: '테조스', logo: 'https://cryptoicon-api.pages.dev/api/icon/xtz' },
    'CKB': { name: '너보스', logo: 'https://cryptoicon-api.pages.dev/api/icon/ckb' },
    'KAVA': { name: '카바', logo: 'https://cryptoicon-api.pages.dev/api/icon/kava' },
    'TOSHI': { name: '토시', logo: 'https://cryptoicon-api.pages.dev/api/icon/toshi' },
    'BARD': { name: '롬바드', logo: 'https://cryptoicon-api.pages.dev/api/icon/bard' },
    'ZRO': { name: '레이어제로', logo: 'https://cryptoicon-api.pages.dev/api/icon/zro' },
    'RAY': { name: '레이디움', logo: 'https://cryptoicon-api.pages.dev/api/icon/ray' },
    'ONDO': { name: '온도파이낸스', logo: 'https://cryptoicon-api.pages.dev/api/icon/ondo' },
    'ZRX': { name: '제로엑스', logo: 'https://cryptoicon-api.pages.dev/api/icon/zrx' },
    'GMT': { name: '스테픈', logo: 'https://cryptoicon-api.pages.dev/api/icon/gmt' },
    'TFUEL': { name: '쎄타퓨엘', logo: 'https://cryptoicon-api.pages.dev/api/icon/tfuel' },
    'XPL': { name: '플라즈마', logo: 'https://cryptoicon-api.pages.dev/api/icon/xpl' },
    'MASK': { name: '마스크네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/mask' },
    'COMP': { name: '컴파운드', logo: 'https://cryptoicon-api.pages.dev/api/icon/comp' },
    'ZETA': { name: '제타체인', logo: 'https://cryptoicon-api.pages.dev/api/icon/zeta' },
    'RED': { name: '레드스톤', logo: 'https://cryptoicon-api.pages.dev/api/icon/red' },
    'TIA': { name: '셀레스티아', logo: 'https://cryptoicon-api.pages.dev/api/icon/tia' },
    'ADA': { name: '에이다', logo: 'https://cryptoicon-api.pages.dev/api/icon/ada' },
    'ELF': { name: '엘프', logo: 'https://cryptoicon-api.pages.dev/api/icon/elf' },
    'STEEM': { name: '스팀', logo: 'https://cryptoicon-api.pages.dev/api/icon/steem' },
    'SOPH': { name: '소폰', logo: 'https://cryptoicon-api.pages.dev/api/icon/soph' },
    'MED': { name: '메디블록', logo: 'https://cryptoicon-api.pages.dev/api/icon/med' },
    '1INCH': { name: '1인치네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/1inch' },
    'MEW': { name: '캣인어독스월드', logo: 'https://cryptoicon-api.pages.dev/api/icon/mew' },
    'ORBS': { name: '오브스', logo: 'https://cryptoicon-api.pages.dev/api/icon/orbs' },
    'RENDER': { name: '렌더토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/render' },
    'STG': { name: '스타게이트파이낸스', logo: 'https://cryptoicon-api.pages.dev/api/icon/stg' },
    'ORCA': { name: '오르카', logo: 'https://cryptoicon-api.pages.dev/api/icon/orca' },
    'BERA': { name: '베라체인', logo: 'https://cryptoicon-api.pages.dev/api/icon/bera' },
    'SIGN': { name: '사인', logo: 'https://cryptoicon-api.pages.dev/api/icon/sign' },
    'VANA': { name: '바나', logo: 'https://cryptoicon-api.pages.dev/api/icon/vana' },
    'DOT': { name: '폴카닷', logo: 'https://cryptoicon-api.pages.dev/api/icon/dot' },
    'MET2': { name: '메테오라', logo: 'https://cryptoicon-api.pages.dev/api/icon/met2' },
    'MBL': { name: '무비블록', logo: 'https://cryptoicon-api.pages.dev/api/icon/mbl' },
    'FLUID': { name: '플루이드', logo: 'https://cryptoicon-api.pages.dev/api/icon/fluid' },
    'BIGTIME': { name: '빅타임', logo: 'https://cryptoicon-api.pages.dev/api/icon/bigtime' },
    'SNT': { name: '스테이터스네트워크토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/snt' },
    'SOL': { name: '솔라나', logo: 'https://cryptoicon-api.pages.dev/api/icon/sol' },
    'QKC': { name: '쿼크체인', logo: 'https://cryptoicon-api.pages.dev/api/icon/qkc' },
    'META': { name: '메타디움', logo: 'https://cryptoicon-api.pages.dev/api/icon/meta' },
    'SAHARA': { name: '사하라에이아이', logo: 'https://cryptoicon-api.pages.dev/api/icon/sahara' },
    'MLK': { name: '밀크', logo: 'https://cryptoicon-api.pages.dev/api/icon/mlk' },
    'SXP': { name: '솔라', logo: 'https://cryptoicon-api.pages.dev/api/icon/sxp' },
    'VTHO': { name: '비토르토큰', logo: 'https://cryptoicon-api.pages.dev/api/icon/vtho' },
    'KITE': { name: '카이트', logo: 'https://cryptoicon-api.pages.dev/api/icon/kite' },
    'MINA': { name: '미나', logo: 'https://cryptoicon-api.pages.dev/api/icon/mina' },
    'MMT': { name: '모멘텀', logo: 'https://cryptoicon-api.pages.dev/api/icon/mmt' },
    'ZORA': { name: '조라', logo: 'https://cryptoicon-api.pages.dev/api/icon/zora' },
    'GAS': { name: '가스', logo: 'https://cryptoicon-api.pages.dev/api/icon/gas' },
    'MNT': { name: '맨틀', logo: 'https://cryptoicon-api.pages.dev/api/icon/mnt' },
    'MOC': { name: '모스코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/moc' },
    'MOODENG': { name: '무뎅', logo: 'https://cryptoicon-api.pages.dev/api/icon/moodeng' },
    'XEC': { name: '이캐시', logo: 'https://cryptoicon-api.pages.dev/api/icon/xec' },
    'MON': { name: '모나드', logo: 'https://cryptoicon-api.pages.dev/api/icon/mon' },
    'ZIL': { name: '질리카', logo: 'https://cryptoicon-api.pages.dev/api/icon/zil' },
    'GAME2': { name: '게임빌드', logo: 'https://cryptoicon-api.pages.dev/api/icon/game2' },
    'STX': { name: '스택스', logo: 'https://cryptoicon-api.pages.dev/api/icon/stx' },
    'FLOCK': { name: '플록', logo: 'https://cryptoicon-api.pages.dev/api/icon/flock' },
    'PROVE': { name: '서싱트', logo: 'https://cryptoicon-api.pages.dev/api/icon/prove' },
    'BSV': { name: '비트코인에스브이', logo: 'https://cryptoicon-api.pages.dev/api/icon/bsv' },
    'SUI': { name: '수이', logo: 'https://cryptoicon-api.pages.dev/api/icon/sui' },
    'SYRUP': { name: '메이플파이낸스', logo: 'https://cryptoicon-api.pages.dev/api/icon/syrup' },
    'BTC': { name: '비트코인', logo: 'https://cryptoicon-api.pages.dev/api/icon/btc' },
    'HOLO': { name: '홀로월드에이아이', logo: 'https://cryptoicon-api.pages.dev/api/icon/holo' },
    'MIRA': { name: '미라네트워크', logo: 'https://cryptoicon-api.pages.dev/api/icon/mira' },
    'SUN': { name: '썬', logo: 'https://cryptoicon-api.pages.dev/api/icon/sun' },
    'ZBT': { name: '제로베이스', logo: 'https://cryptoicon-api.pages.dev/api/icon/zbt' },
    'ONG': { name: '온톨로지가스', logo: 'https://cryptoicon-api.pages.dev/api/icon/ong' },
    'BTT': { name: '비트토렌트', logo: 'https://cryptoicon-api.pages.dev/api/icon/btt' },
    'ENSO': { name: '엔소', logo: 'https://cryptoicon-api.pages.dev/api/icon/enso' },
    'ONT': { name: '온톨로지', logo: 'https://cryptoicon-api.pages.dev/api/icon/ont' },
    'SOMI': { name: '솜니아', logo: 'https://cryptoicon-api.pages.dev/api/icon/somi' },
    'DEEP': { name: '딥북', logo: 'https://cryptoicon-api.pages.dev/api/icon/deep' },
    'STRAX': { name: '저트라', logo: 'https://cryptoicon-api.pages.dev/api/icon/strax' },
    'ICX': { name: '아이콘', logo: 'https://cryptoicon-api.pages.dev/api/icon/icx' },
    'POLYX': { name: '폴리매쉬', logo: 'https://cryptoicon-api.pages.dev/api/icon/polyx' },
    'MATIC': { name: '폴리곤', logo: 'https://cryptoicon-api.pages.dev/api/icon/matic' }
};

/**
 * Get coin information with fallback
 * @param {string} coin - Coin symbol (e.g., 'BTC', 'ETH')
 * @returns {object} - { name: string, logo: string }
 */
function getCoinInfo(coin) {
    const upperCoin = coin.toUpperCase();
    if (COIN_INFO[upperCoin]) {
        return COIN_INFO[upperCoin];
    }
    // Fallback: use dynamic logo API
    return {
        name: coin,
        logo: `https://cryptoicon-api.pages.dev/api/icon/${coin.toLowerCase()}`
    };
}

/**
 * Extract coin symbol from market code
 * @param {string} market - Market code (e.g., 'KRW-BTC')
 * @returns {string} - Coin symbol (e.g., 'BTC')
 */
function extractCoinSymbol(market) {
    if (!market) return '';
    return market.split('-')[1] || market;
}
